apiVersion: v1
kind: ConfigMap
metadata:
  name: apr3-existingmodelserver-1-model-config
data:
  MODEL_ENDPOINT: "https://ollama-model-service-apicast-production.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com:443/v1"
  MODEL_NAME: "mistral:7b"
